export enum Colors {
  PRIMARY_DARK = 'PRIMARY_DARK',
  PRIMARY_SHADOW = 'PRIMARY_SHADOW',
  PRIMARY_STANDARD = 'PRIMARY_STANDARD',
  PRIMARY_LIGHT = 'PRIMARY_LIGHT',
  SECONDARY_ALERT = 'SECONDARY_ALERT',
  SECONDARY_CAUTION = 'SECONDARY_CAUTION',
  SECONDARY_ACCENT = 'SECONDARY_ACCENT',
  SECONDARY_HIGHLIGHT = 'SECONDARY_HIGHLIGHT',
  SECONDARY_PALE = 'SECONDARY_PALE',
  GREY_SUPER_DARK = 'GREY_SUPER_DARK',
  GREY_DARK = 'GREY_DARK',
  GREY_SHADOW = 'GREY_SHADOW',
  GREY_NEUTRAL = 'GREY_NEUTRAL',
  GREY_LIGHT = 'GREY_LIGHT',
  GREY_SUPER_LIGHT = 'GREY_SUPER_LIGHT',
  WHITE = 'WHITE',
  TRANSPARENT = 'TRANSPARENT'
}

export const defaultColors = {}
